name: meme_generator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.3.0 # Dart SDK version
  flutter: 3.19.0 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  json_annotation: ^4.8.1
  screenshot: ^2.1.0
  share_plus: ^7.2.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  xsoulspace_lints: ^0.0.10

  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true